### ISSUE TITLE
usage examples from SE not working

### ISSUE THREAD

**Issue by lucainnocenti** [b3m2a1/mathematica-DocGen#1]
Hi. Thanks for uploading this!
Could you put a simple usage example on the README though? I tried with the syntax shown in [your SE post](https://mathematica.stackexchange.com/questions/146670/automating-documentation-generation/146671#146671) but `GenerateRefPages` does not seem to be exposed and `GenerateDocumentation` throws a bunch of errors and produces a broken Doc page:

![screenshot 2017-08-14 12 19 22](https://user-images.githubusercontent.com/10957113/29269723-edb0fabc-80ea-11e7-85a6-08feec1bf6b2.png)

![screenshot 2017-08-14 12 20 42](https://user-images.githubusercontent.com/10957113/29269733-fea3711a-80ea-11e7-85c1-6f247ca73c55.png)

I tried `GenerateDocumentation` on a few other packages but they throw the same errors.

**Comment by b3m2a1** [comment]
Oh sure thing. The function itself has changed name. I'll put up a basic README and I'll link to the docs for the package, too.

**Comment by b3m2a1** [comment]
@lucainnocenti that should be patched. Main issue was that my subpaclet-ing mechanism wasn't quite expansive enough. Try it now.

**Comment by lucainnocenti** [comment]
great, it now works perfectly. Thanks!
